name: tazbeet
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.6+6

environment:
  sdk: ^3.8.1

dependencies:
  audioplayers: ^6.5.1
  bloc: ^9.0.0
  cloud_firestore: ^5.6.11
  confetti: ^0.8.0
  connectivity_plus: ^7.0.0
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  file_picker: ^10.3.3
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_crashlytics: ^4.3.6
  firebase_storage: ^12.4.9
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  flutter_facebook_auth: ^7.1.1
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  flutter_tts: ^4.1.0
  google_api_availability: ^5.0.1
  google_sign_in: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  icons_launcher: ^3.0.2
  image_picker: ^1.1.2
  in_app_update: ^4.2.2
  intl: ^0.20.2
  lottie: ^3.1.3
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  percent_indicator: ^4.2.3
  permission_handler: ^12.0.1
  provider: ^6.1.2
  reorderables: ^0.6.0
  share_plus: ^10.1.4
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  syncfusion_flutter_gauges: ^31.1.19
  timezone: ^0.10.1
  tutorial_coach_mark: ^1.3.1
  uuid: ^4.5.1
  workmanager: ^0.9.0+3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: TajawalR
      fonts:
        - asset: assets/fonts/TajawalR.ttf

  assets:
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/sounds/
    - assets/fonts/
    - assets/logo/

icons_launcher:
  image_path: "assets/logo/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
    web:
      enable: true
