// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlkK-WpMW4Wyw7qS2LRjqcx1iMgtCwJJw',
    appId: '1:59269490691:web:d2e1922bdeb47467b70636',
    messagingSenderId: '59269490691',
    projectId: 'tazbeet-570e2',
    authDomain: 'tazbeet-570e2.firebaseapp.com',
    storageBucket: 'tazbeet-570e2.firebasestorage.app',
    measurementId: 'G-X1LQF37HY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuu6ekQ5rCqujk9ajOJdxxeOdDGus--Bc',
    appId: '1:59269490691:android:5471588776016168b70636',
    messagingSenderId: '59269490691',
    projectId: 'tazbeet-570e2',
    storageBucket: 'tazbeet-570e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChJFhhx0s34mzxta7LXPGL_KqJm4iTAEQ',
    appId: '1:59269490691:ios:b9844a3dc408e705b70636',
    messagingSenderId: '59269490691',
    projectId: 'tazbeet-570e2',
    storageBucket: 'tazbeet-570e2.firebasestorage.app',
    androidClientId: '59269490691-1bhscucshuqodvvh3b3m0dvct511vlu2.apps.googleusercontent.com',
    iosClientId: '59269490691-fl4b8m56aqsoo746m1hpqo60j22al495.apps.googleusercontent.com',
    iosBundleId: 'com.company.tazbeet',
  );
}
