// Mocks generated by Mockito 5.4.5 from annotations
// in tazbeet/test/blocs/task_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:tazbeet/l10n/app_localizations.dart' as _i9;
import 'package:tazbeet/models/category.dart' as _i7;
import 'package:tazbeet/models/task.dart' as _i4;
import 'package:tazbeet/repositories/category_repository.dart' as _i6;
import 'package:tazbeet/repositories/task_repository.dart' as _i3;
import 'package:tazbeet/services/notification_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<List<_i4.Task>> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: _i2.Future<List<_i4.Task>>.value(<_i4.Task>[]),
      ) as _i2.Future<List<_i4.Task>>);

  @override
  _i2.Future<_i4.Task?> getTaskById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getTaskById,
          [id],
        ),
        returnValue: _i2.Future<_i4.Task?>.value(),
      ) as _i2.Future<_i4.Task?>);

  @override
  _i2.Future<void> addTask(_i4.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #addTask,
          [task],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> updateTask(_i4.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> updateTasks(List<_i4.Task>? tasks) => (super.noSuchMethod(
        Invocation.method(
          #updateTasks,
          [tasks],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> deleteTask(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> deleteTasks(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteTasks,
          [ids],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<List<_i4.Task>> getTasksByCategory(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTasksByCategory,
          [categoryId],
        ),
        returnValue: _i2.Future<List<_i4.Task>>.value(<_i4.Task>[]),
      ) as _i2.Future<List<_i4.Task>>);

  @override
  _i2.Future<List<_i4.Task>> getTasksDueToday() => (super.noSuchMethod(
        Invocation.method(
          #getTasksDueToday,
          [],
        ),
        returnValue: _i2.Future<List<_i4.Task>>.value(<_i4.Task>[]),
      ) as _i2.Future<List<_i4.Task>>);

  @override
  _i2.Future<List<_i4.Task>> getOverdueTasks() => (super.noSuchMethod(
        Invocation.method(
          #getOverdueTasks,
          [],
        ),
        returnValue: _i2.Future<List<_i4.Task>>.value(<_i4.Task>[]),
      ) as _i2.Future<List<_i4.Task>>);

  @override
  _i2.Future<void> clearAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #clearAllTasks,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<T> monitorAsync<T>(
    String? operationName,
    _i2.Future<T> Function()? operation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #monitorAsync,
          [
            operationName,
            operation,
          ],
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #monitorAsync,
                  [
                    operationName,
                    operation,
                  ],
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(
              this,
              Invocation.method(
                #monitorAsync,
                [
                  operationName,
                  operation,
                ],
              ),
            ),
      ) as _i2.Future<T>);

  @override
  T monitorSync<T>(
    String? operationName,
    T Function()? operation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #monitorSync,
          [
            operationName,
            operation,
          ],
        ),
        returnValue: _i5.dummyValue<T>(
          this,
          Invocation.method(
            #monitorSync,
            [
              operationName,
              operation,
            ],
          ),
        ),
      ) as T);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i6.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<List<_i7.Category>> getAllCategories() => (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
        ),
        returnValue: _i2.Future<List<_i7.Category>>.value(<_i7.Category>[]),
      ) as _i2.Future<List<_i7.Category>>);

  @override
  _i2.Future<_i7.Category?> getCategoryById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getCategoryById,
          [id],
        ),
        returnValue: _i2.Future<_i7.Category?>.value(),
      ) as _i2.Future<_i7.Category?>);

  @override
  _i2.Future<void> addCategory(_i7.Category? category) => (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [category],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> updateCategory(_i7.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [category],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> deleteCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<List<_i7.Category>> getDefaultCategories() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultCategories,
          [],
        ),
        returnValue: _i2.Future<List<_i7.Category>>.value(<_i7.Category>[]),
      ) as _i2.Future<List<_i7.Category>>);

  @override
  _i2.Future<void> createDefaultCategories() => (super.noSuchMethod(
        Invocation.method(
          #createDefaultCategories,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> updateCategoryTaskCounts(List<dynamic>? tasks) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategoryTaskCounts,
          [tasks],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i8.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<bool> hasNotificationPermission() => (super.noSuchMethod(
        Invocation.method(
          #hasNotificationPermission,
          [],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  _i2.Future<bool> requestNotificationPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestNotificationPermission,
          [],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  _i2.Future<void> scheduleTaskReminder(_i4.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #scheduleTaskReminder,
          [task],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> scheduleMoodCheckInNotifications(
    List<String>? times, {
    _i9.AppLocalizations? l10n,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleMoodCheckInNotifications,
          [times],
          {#l10n: l10n},
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> cancelMoodCheckInNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelMoodCheckInNotifications,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> cancelTaskReminder(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #cancelTaskReminder,
          [taskId],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> showTaskDueNotification(_i4.Task? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #showTaskDueNotification,
          [task],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> showTaskCompletedNotification(_i4.Task? task) =>
      (super.noSuchMethod(
        Invocation.method(
          #showTaskCompletedNotification,
          [task],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> scheduleTestReminder() => (super.noSuchMethod(
        Invocation.method(
          #scheduleTestReminder,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> showTestNotificationNow() => (super.noSuchMethod(
        Invocation.method(
          #showTestNotificationNow,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> showImmediateNotification(
    String? title,
    String? body, {
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showImmediateNotification,
          [
            title,
            body,
          ],
          {#payload: payload},
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> showTestMoodNotificationNow({_i9.AppLocalizations? l10n}) =>
      (super.noSuchMethod(
        Invocation.method(
          #showTestMoodNotificationNow,
          [],
          {#l10n: l10n},
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> scheduleTestMoodNotification({_i9.AppLocalizations? l10n}) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleTestMoodNotification,
          [],
          {#l10n: l10n},
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> rescheduleAllReminders(List<_i4.Task>? tasks) =>
      (super.noSuchMethod(
        Invocation.method(
          #rescheduleAllReminders,
          [tasks],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> openNotificationSettings() => (super.noSuchMethod(
        Invocation.method(
          #openNotificationSettings,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<bool> areNotificationsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #areNotificationsEnabled,
          [],
        ),
        returnValue: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  _i2.Future<List<_i10.PendingNotificationRequest>> getPendingNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingNotifications,
          [],
        ),
        returnValue: _i2.Future<List<_i10.PendingNotificationRequest>>.value(
            <_i10.PendingNotificationRequest>[]),
      ) as _i2.Future<List<_i10.PendingNotificationRequest>>);

  @override
  _i2.Future<List<_i10.PendingNotificationRequest>>
      getPendingMoodNotifications() => (super.noSuchMethod(
            Invocation.method(
              #getPendingMoodNotifications,
              [],
            ),
            returnValue:
                _i2.Future<List<_i10.PendingNotificationRequest>>.value(
                    <_i10.PendingNotificationRequest>[]),
          ) as _i2.Future<List<_i10.PendingNotificationRequest>>);

  @override
  _i2.Future<void> rescheduleMoodNotifications({_i9.AppLocalizations? l10n}) =>
      (super.noSuchMethod(
        Invocation.method(
          #rescheduleMoodNotifications,
          [],
          {#l10n: l10n},
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> cancelAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllNotifications,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
}
